builds:
  - binary: remindme
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: remindme
    homepage: "https://github.com/n0rdy/remindme"
    tap:
      owner: n0rdy
      name: homebrew-n0rdy
    commit_author:
      name: n0rdy
      email: n0rdy@pm.me

checksum:
  name_template: 'checksums.txt'